services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: anabol1ks
      POSTGRES_PASSWORD: 12341
      POSTGRES_DB: realty
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "12341"]
    environment:
      - REDIS_PASSWORD=12341
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  pgdata:
  redis_data:
