// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/valuation": {
            "get": {
                "description": "Возвращает общий список сохранённых оценок (thin-формат)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "valuation"
                ],
                "summary": "Список сохранённых отчётов",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Максимум записей",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Смещение",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.ValuationListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/valuation/address": {
            "post": {
                "description": "Вызывает ML-сервис RealVal для расчёта рыночной ставки аренды и сохраняет полный отчёт",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "valuation"
                ],
                "summary": "Оценка аренды квартиры по адресу",
                "parameters": [
                    {
                        "description": "Параметры квартиры для оценки",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.AddressValuationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.AddressValuationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/valuation/{id}": {
            "get": {
                "description": "Читает сохранённый отчёт из БД и возвращает краткую версию для фронта",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "valuation"
                ],
                "summary": "Получить краткий отчёт об оценке по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID отчёта (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.AddressValuationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/valuation/{id}/pdf": {
            "get": {
                "description": "Возвращает PDF-файл с полным отчетом по оценке аренды",
                "produces": [
                    "application/pdf"
                ],
                "tags": [
                    "valuation"
                ],
                "summary": "PDF-отчет по оценке",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID отчёта (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.AddressValuationComparableSummary": {
            "type": "object",
            "properties": {
                "area_total": {
                    "type": "number",
                    "example": 83
                },
                "distance_km": {
                    "type": "number",
                    "example": 0.01
                },
                "metro_station": {
                    "type": "string",
                    "example": "Славянский бульвар"
                },
                "price_rub": {
                    "type": "number",
                    "example": 195000
                },
                "rooms": {
                    "type": "integer",
                    "example": 2
                },
                "url": {
                    "description": "\u003c-- ДОБАВЛЕНО",
                    "type": "string",
                    "example": "https://realty.yandex.ru/offer/123456/"
                }
            }
        },
        "handlers.AddressValuationObjectSummary": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "Нежинская улица, 1к1"
                },
                "area_total": {
                    "type": "number",
                    "example": 90
                },
                "city": {
                    "type": "string",
                    "example": "Москва"
                },
                "floor": {
                    "type": "integer",
                    "example": 24
                },
                "floors_total": {
                    "type": "integer",
                    "example": 31
                },
                "house_material": {
                    "type": "string",
                    "example": "монолит"
                },
                "rooms": {
                    "type": "integer",
                    "example": 2
                },
                "year_built": {
                    "type": "integer",
                    "example": 2008
                }
            }
        },
        "handlers.AddressValuationPriceSummary": {
            "type": "object",
            "properties": {
                "currency": {
                    "type": "string",
                    "example": "RUB"
                },
                "deal_type": {
                    "type": "string",
                    "example": "rent_long"
                },
                "interval_high_rub": {
                    "type": "number",
                    "example": 228504.7
                },
                "interval_low_rub": {
                    "type": "number",
                    "example": 120077.1
                },
                "prediction_rub": {
                    "type": "number",
                    "example": 165644.8
                }
            }
        },
        "handlers.AddressValuationRequest": {
            "type": "object",
            "required": [
                "address",
                "area_total",
                "city",
                "rooms"
            ],
            "properties": {
                "address": {
                    "type": "string",
                    "example": "Нежинская улица, 1к1"
                },
                "area_kitchen": {
                    "type": "number",
                    "example": 20
                },
                "area_living": {
                    "type": "number",
                    "example": 65
                },
                "area_total": {
                    "type": "number",
                    "example": 90
                },
                "city": {
                    "type": "string",
                    "example": "Москва"
                },
                "condition": {
                    "type": "string",
                    "example": "без отделки"
                },
                "floor": {
                    "type": "integer",
                    "example": 24
                },
                "floors_total": {
                    "type": "integer",
                    "example": 31
                },
                "house_material": {
                    "type": "string",
                    "example": "монолит"
                },
                "rooms": {
                    "type": "integer",
                    "example": 2
                },
                "with_text": {
                    "type": "boolean",
                    "example": true
                },
                "year_built": {
                    "type": "integer",
                    "example": 2008
                }
            }
        },
        "handlers.AddressValuationResponse": {
            "type": "object",
            "properties": {
                "comparables": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.AddressValuationComparableSummary"
                    }
                },
                "object": {
                    "$ref": "#/definitions/handlers.AddressValuationObjectSummary"
                },
                "price": {
                    "$ref": "#/definitions/handlers.AddressValuationPriceSummary"
                },
                "report_id": {
                    "type": "string"
                },
                "text": {
                    "$ref": "#/definitions/handlers.AddressValuationTextSummary"
                }
            }
        },
        "handlers.AddressValuationTextSummary": {
            "type": "object",
            "properties": {
                "factors_summary": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "summary_long": {
                    "type": "string",
                    "example": "Развёрнутое описание оценки..."
                },
                "summary_short": {
                    "type": "string",
                    "example": "Квартира в городе Москва..."
                }
            }
        },
        "handlers.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "something went wrong"
                }
            }
        },
        "handlers.ValuationListItem": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "Нежинская улица, 1к1"
                },
                "city": {
                    "type": "string",
                    "example": "Москва"
                },
                "created_at": {
                    "type": "string"
                },
                "deal_type": {
                    "type": "string",
                    "example": "rent_long"
                },
                "id": {
                    "type": "string",
                    "example": "d9a3f3b6-..."
                },
                "interval_high_rub": {
                    "type": "number",
                    "example": 228504.7
                },
                "interval_low_rub": {
                    "type": "number",
                    "example": 120077.1
                },
                "prediction_rub": {
                    "type": "number",
                    "example": 165644.8
                },
                "summary_short": {
                    "type": "string",
                    "example": "Квартира в городе Москва..."
                }
            }
        },
        "handlers.ValuationListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.ValuationListItem"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
